services:
  octoeverywhere-bambu-connect:
    image: octoeverywhere/octoeverywhere:latest
    environment:
        # Requried to set the docker conntainer in Bambu Connect mode.
      - COMPANION_MODE=bambu
        # https://octoeverywhere.com/s/access-code
      - ACCESS_CODE=XXXXXXXX
        # https://octoeverywhere.com/s/bambu-sn
      - SERIAL_NUMBER=XXXXXXXXXXXXXXX
        # https://octoeverywhere.com/s/bambu-ip
      - PRINTER_IP=XXX.XXX.XXX.XXX

    volumes:
      # This can also be an absolute path as well.
      - ./data:/data
