version: '3.8'

services:
  # Homepage Dashboard - Central landing page
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: print-hub-dashboard
    restart: unless-stopped
    ports:
      - "80:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/homepage:/app/config
    environment:
      PUID: 1000
      PGID: 1000
    networks:
      - print-hub-network

  # Reverse Proxy for routing to submodules
  nginx-proxy:
    image: nginx:alpine
    container_name: print-hub-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - homepage
    networks:
      - print-hub-network

networks:
  print-hub-network:
    driver: bridge
    external: false

volumes:
  homepage-config:
