---
providers:
  docker:
    endpoint: unix:///var/run/docker.sock

settings:
  title: Print Hub Dashboard
  background:
    image: hthttps://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
    blur: sm
    brightness: 30
    saturate: 50

layout:
  - 3D Printing Services:
      style: row
      columns: 3
  - Additional Services:
      style: row
      columns: 3
