---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- 3D Printing Services:
    - OctoPrint:
        href: http://{{HOMEPAGE_VAR_HOST_IP}}/octoprints/
        description: Marlin 3D Printer Management (OctoPrint Stack)
        icon: octoprint.png
        ping: http://{{HOMEPAGE_VAR_HOST_IP}}/octoprints/

    - Klipper UI:
        href: http://{{HOMEPAGE_VAR_HOST_IP}}/klipper
        description: Klipper Web Interface (Prind Stack)
        icon: klipper.png
        ping: http://{{HOMEPAGE_VAR_HOST_IP}}/klipper

    - Bambu Connect:
        href: https://octoeverywhere.com/dashboard
        description: Bamboo Labs Integration
        icon: code-server.png
        ping: https://octoeverywhere.com

- Additional Services:
    - Portainer:
        href: http://{{HOMEPAGE_VAR_HOST_IP}}/portainer
        description: Manage the Docker containers individually through a web interface
        icon: portainer.png
        ping: http://{{HOMEPAGE_VAR_HOST_IP}}/portainer

    - Spoolman:
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:80/spoolman
        description: Filament Management (Prind Stack)
        icon: spoolman.png
        ping: http://{{HOMEPAGE_VAR_HOST_IP}}:80

    - "OctoEverwhere: Remote Printer Access":
        href: https://octoeverywhere.com/dashboard
        description: Used for Bamboo Labs Integration but works with everything
        icon: code-server.png
        ping: https://octoeverywhere.com
