---
title: Print Hub Dashboard
subtitle: 3D Printing Services Management
logo: https://gethomepage.dev/assets/favicon.ico
headerStyle: clean
startUrl: /

layout:
  3D Printing Services:
    style: row
    columns: 3
  Additional Services:
    style: row
    columns: 3

color: slate

theme: dark

background:
  image: /images/background.jpg
  blur: sm
  saturate: 50
  brightness: 30

favicon: /favicon.ico

fiveColumns: false

hideVersion: false
